const motd = [
"Tout ça donne Sewaf.",
"haha html go &lt;br&gt;",
"L'hypothèque. C'est comme une bibliothèque sauf qu'on y emprunte des hippopotames.",
"4",
"5",
"6",
"7",
"8",
"9",
"10",
"11",
"12",
"13",
"14",
"15",
"16",
"17",
"18",
"19",
"20",
"21",
"Le beurre, l'argent du beurre, et un peu de crème pour le goût.",
"23",
"24",
"25",
"26",
"I'll tell you what I want, what I really really want.",
"La logique et le bon sens n'ont pas de place dans cette maison.",
"29",
"dummy dummy dummy a man after midnight.",
"31",
];

document.write(motd[new Date().getDate()-1]);