const motd = [
"Tout ça donne Sewaf.",
"haha html go &lt;br&gt;",
"L'hypothèque. C'est comme une bibliothèque sauf qu'on y emprunte des hippopotames.",
"You have failed at life. Please reset.",
"What was the error message you closed without reading?",
"6",
"7",
"keyboard.insert(\"coffee\");",
"Y2K compliant",
"Not enough ink to scan.",
"11",
"12",
"13",
"14",
"15",
"help me I'm in the cell E4",
"Suddently, pineapples.",
"Gotta catch'em all.",
"THUS Bond theme.",
"20",
"21",
"Le beurre, l'argent du beurre, et un peu de crème pour le goût.",
"23",
"#define true random()&lt;8",
`${(11-((new Date()).getMonth()) == 0) ? "*keeps trying to draw a christmas tree in C*" : 
11-((new Date()).getMonth()) + " month" + (11-((new Date()).getMonth()) > 1 ? "s" : "") + " until Christmas"}`,
"Treat warnings as errors.",
"I'll tell you what I want, what I really really want.",
"La logique et le bon sens n'ont pas de place dans cette maison.",
"object.move(along);",
"dummy dummy dummy a man after midnight.",
"31",
];

document.write(motd[new Date().getDate()-1]);